services:
  db-postgres:
    container_name: db-postgres
    build:
      context: docker/postgres
      dockerfile: Dockerfile-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      RXFA_PASSWORD_HASH: ${RXFA_PASSWORD_HASH:-$$2a$$12$$8Edde3c7GlrCTxHFVlXasOWDmtY1RQ.3Vwh7BEu9RWc7fWNSodPJ.}
      ADMIN_PASSWORD_HASH: ${ADMIN_PASSWORD_HASH:-$$2a$$12$$qWmekXEazYubKbsAzCTRPO9RwixCo1RlwyCpjD/MMN7rnir9l25wq}
    ports:
      - "5432:5432"

  chimp:
    build:
      context: .
      dockerfile: docker/Dockerfile-chimp
    environment:
      PORT: 8080
      DB_URL: jdbc:postgresql://db-postgres:5432/${POSTGRES_DB}?user=${POSTGRES_USER}&password=${POSTGRES_PASSWORD}

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile-nginx
    ports:
      - "8080:8080"
    depends_on:
        - chimp

  ubuntu:
    container_name: ubuntu
    build:
      context: .
      dockerfile: docker/Dockerfile-ubuntu
    tty: true

